global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'account'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'account:8082' ]
  - job_name: 'auth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'auth:8086' ]
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver:8761' ]
  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver:8073' ]
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8084' ]
